server:
  port: 8085

spring:
  application:
    name: identity-service
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/identity_service_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/sagittarius-realm

app:
  jwt:
    secret: ${JWT_SECRET_KEY}
    expiration: ${JWT_EXPIRATION_TIME}
  keycloak:
    username: ${KC_ADMIN_USER}
    password: ${KC_ADMIN_PASS}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

grpc:
  client:
    payment-service:
      address: static://localhost:9093
      negotiation-type: plaintext