CREATE TABLE t_inventory
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sku_code          VARCHAR(255)                            NOT NULL,
    quantity          INTEGER,
    reserved_quantity INTEGER,
    reorder_level     INTEGER,
    last_updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_t_inventory PRIMARY KEY (id)
);

CREATE TABLE t_outbox_events
(
    id             UUID         NOT NULL,
    aggregate_type VARCHAR(255) NOT NULL,
    aggregate_id   VARCHAR(255) NOT NULL,
    type           VARCHAR(255) NOT NULL,
    payload        TEXT         NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_t_outbox_events PRIMARY KEY (id)
);

CREATE TABLE t_processed_orders
(
    order_number   VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_t_processed_orders PRIMARY KEY (order_number)
);

ALTER TABLE t_inventory
    ADD CONSTRAINT uc_t_inventory_sku_code UNIQUE (sku_code);