CREATE TABLE t_order_line_items
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sku_code VARCHAR(255)                            NOT NULL,
    price    DECIMAL                                 NOT NULL,
    quantity INTEGER                                 NOT NULL,
    order_id BIGINT,
    CONSTRAINT pk_t_order_line_items PRIMARY KEY (id)
);

CREATE TABLE t_orders
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_number     VARCHAR(255)                            NOT NULL,
    user_id          VARCHAR(255)                            NOT NULL,
    email            VARCHAR(255),
    shipping_address VARCHAR(255),
    total_amount     DECIMAL                                 NOT NULL,
    status           VARCHAR(255)                            NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_t_orders PRIMARY KEY (id)
);

CREATE TABLE t_outbox_events
(
    id             UUID         NOT NULL,
    aggregate_type VARCHAR(255) NOT NULL,
    aggregate_id   VARCHAR(255) NOT NULL,
    type           VARCHAR(255) NOT NULL,
    payload        TEXT         NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_t_outbox_events PRIMARY KEY (id)
);

ALTER TABLE t_orders
    ADD CONSTRAINT uc_t_orders_order_number UNIQUE (order_number);

ALTER TABLE t_order_line_items
    ADD CONSTRAINT FK_T_ORDER_LINE_ITEMS_ON_ORDER FOREIGN KEY (order_id) REFERENCES t_orders (id);