input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

output {
  elasticsearch {
    hosts => ["http://sagittarius-elasticsearch:9200"]
    index => "sagittarius-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}